{
 "title": "Debezium & Kafka Connect Metrics",
 "tags": [
  "kafka",
  "debezium"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Connect: количество коннекторов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_count",
     "legendFormat": "connectors"
    }
   ]
  },
  {
   "title": "Kafka Connect: количество задач",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_task_count",
     "legendFormat": "tasks"
    }
   ]
  },
  {
   "title": "Задачи коннекторов (running / failed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_running_tasks",
     "legendFormat": "{{connector}} - running"
    },
    {
     "expr": "kafka_connect_connector_failed_tasks",
     "legendFormat": "{{connector}} - failed"
    }
   ]
  }
 ]
}